import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React ,{useState} from 'react';
import $ from "jquery";

export default function Home() {

  const [FirstName,setFirstName]=useState("");
  const [LastName,setLastName]=useState("");
  const [Email,setEmail]=useState("");
  const [PhoneNumber,setPhoneNumber]=useState("");

  const [FirstNameerr,setFirstNameerr]=useState("");
  const [LastNameerr,setLastNameerr]=useState("");
  const [Emailerr,setEmailerr]=useState("");
  const [PhoneNumbererr,setPhoneNumbererr]=useState("");
  async function putValue(e)
  {
    e.preventDefault();
    var namecheck=/^[a-zA-Z]+$/;
    var lnamecheck=/^[a-zA-Z]+$/;
    if (FirstName==="") {
        setFirstNameerr("fill the fields!!");
        return false;
    }
    else{
        if (namecheck.test( FirstName ))
        {
            if (/^\s+$/.test(FirstName)) {
                setFirstNameerr("Enert First name..");
                return false;
            }
        }else{
            setFirstNameerr("enter a valid name");
                return false;
        }
        setFirstNameerr("");
    }

  if (LastName==="") {
      setLastNameerr("fill the fields!!");
      return false;
  }
  else{
      if (lnamecheck.test( LastName ))
      {
          if (/^\s+$/.test(LastName)) {
              setLastNameerr("Enter Last name");
              return false;
          }
      }else{
          setLastNameerr("enter a valid last name");
              return false;
      }
      setLastNameerr("");
  }
  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    if (Email==="") {
        setEmailerr("yo can't leave it blank");
        return false;
    }
    else{
        if(!regex.test(Email))
        {
            var regex_sec=/^[^ ]+@[^ ]+\.[a-z]{2,3}$/;
            if(!regex_sec.test(Email))
            {
            setEmailerr("invalid email")
            return false;
            }
        }
        setEmailerr("");
    }
    var cno=/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/;
    if (PhoneNumber==="") {
        setPhoneNumbererr("yo can't leave it blank");
        return false;
    }
    else{
        if(!cno.test(PhoneNumber))
        {
            setPhoneNumbererr("invalid contact no")
            return false;
           
        }
        setPhoneNumbererr("");
    }




    let valueForm = {FirstName,LastName,Email,PhoneNumber};

     fetch('/api/form', {
      method : 'POST',
      headers :{ 'Content-Type' : 'application/json'},
      body : JSON.stringify(valueForm)
      }).then(response => response.json())
        .then(data => {
          if(data.status === 'success')
          {
            $("#msg").html("Data Stored");
            $('#formID').trigger("reset");
            
          } 
          else 
          {
            $("#errors").html("Invalid Data");
          }
      })
  }  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div id="msg"> </div>
        <p id="alert"></p>
        <p id="errors"></p>
        <form id="formID"> 
          <div className="single-field">
            <label for="first">First name</label>
            <input type="text" id="first" required name="first" onChange={(e)=>setFirstName(e.target.value)} />
            <span className='text-danger'>{FirstNameerr}</span>
          </div>
          <div className="single-field">
            <label for="last">Last name</label>
            <input type="text" id="last" name="last" onChange={(e)=>setLastName(e.target.value)} />
            <span className='text-danger'>{LastNameerr}</span>
          </div>
          <div className="single-field">
            <label for="email">Email</label>
            <input type="text" id="email" name="email" onChange={(e)=>setEmail(e.target.value)} />
            <span className='text-danger'>{Emailerr}</span>
          </div>
          <div className="single-field">
            <label for="phone">Phone Number</label>
            <input type="text" id="phone" name="phone" onChange={(e)=>setPhoneNumber(e.target.value)} />
            <span className='text-danger'>{PhoneNumbererr}</span>
          </div>
          <button className="form-button" onClick={putValue}>Submit</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <style jsx>{`
        #formID{border:1px solid #bdbdbd; padding: 40px; width: 450px;}
        .single-field{margin-bottom: 20px;}
        .single-field label{margin-bottom: 5px; display: block;}
        .single-field input{display: block; width: 100%; border: 1px solid #757575; padding: 10px 20px;}
        .form-button{display: block; width:100%; border: 1px solid #757575; background: #757575; padding: 10px 25px; font-size: 15px; color: #fff; text-shadow: 0.5px 1px 2px #000; text-transform: uppercase; letter-spacing: 1px; cursor: pointer;}
      `}</style>

    </div>
  )
}
